# Change these first
owner: Three-Times-Reborned # Your GitHub organization or username, where this repository lives
repo: Discord-URL-status # The name of this repository

sites:
  - name: Discord invite URL
    url: https://dc.ttr3.eu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.ttr3.eu
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Three Times Reborned Uptime"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Charlie Cloud Status
      href: https://status.charlie-cloud.hu
    - title: Charlie Cloud Node uptime
      href: https://uptime.charlie-cloud.hu

  metaTags:
    - name: "robots"
      content: "noindex"
  theme: night

status-page:
  robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
